### ISSUE TITLE
Feature Request - Add configuration to cache other methods

### ISSUE THREAD

**Issue by tailtq** [darkweak/souin#187]
Can we have a feature to set caching methods dynamically, not only GET? Below is the example:
```
- traefik.http.middlewares.http-cache.plugin.souin-plugin.cache-methods=GET,POST,PUT,PATCH
- traefik.http.middlewares.http-cache.plugin.souin-plugin.invalidate-cache-methods=DELETE
```
In many projects, we often use methods like `POST`, `PUT`, ... to retrieve the data when the inputs are heavy or need to be encrypted. Therefore, I think this feature will be useful.

Thank you.

**Comment by darkweak** [comment]
Hi @tailtq I will investigate about the side-effects to implement this because IMHO I'll have to manage the keys another way.
I don't know what to use to avoid collisions while we retrieve the cached data because if a user `A` send a request to the `/resource` endpoint with a JSON body like `{"keyA": "any"}` and another user `B` send the request on the same endpoint with another body shouldn't have the same response.

I agree with you that would be useful but hard to implement I guess. 😅

**Comment by tailtq** [comment]
Yes, the strategy to manage the keys will be different because the key should contain the data. You can leave the issue open to implement later or feel free to close it. Thanks.

**Comment by darkweak** [comment]
Maybe using a hash could do the trick ? WDYT ?

**Comment by tailtq** [comment]
@darkweak Yes, I think it could. I tried [another cache library](https://github.com/tkem/cachetools) before and their approach to getting the key from the parameters is hashing. What do you think about the data which is allowed to cache? It should be text, shouldn't it?

**Comment by darkweak** [comment]
Update, I'm currently working on it and I'll try to partially support the GraphQ cache in the same time.
