### ISSUE TITLE
Tyk plugin:  stale-while-revalidate

### ISSUE THREAD

**Issue by acaporrini** [darkweak/souin#336]
Hi all, 

I'm trying to use souin as Tyk plugin with Tyk Gateway 4.0.6 and is not clear to me how to configure it to enable stale-while-revalidate cache control. 

My Tyk API definition:

```
{
  "name": "Test API",
  "slug": "Test API",
  "api_id": "test_api",
  "org_id": "test",
  "use_keyless": false,
  "auth": {
    "auth_header_name": "X-Api-Key",
    "strip_auth_data": true
  },
  "definition": {
    "location": "url"
  },
  "version_data": {
    "not_versioned": false,
    "versions": {
      "v1": {
        "name": "v1",
        "use_extended_paths": false
      }
    }
  },
  "proxy": {
    "listen_path": "/test/",
    "enable_load_balancing" : true,
    "target_list": [
      " https://test.com"
    ],
    "strip_listen_path": true
  },
  "global_rate_limit" : {
    "rate": 10000,
    "per": 60
  },

  "custom_middleware": {
    "pre": [],
    "post": [
      {
        "name": "SouinRequestHandler",
        "path": "./middleware/souin-plugin.so"
      }
    ],
    "response": [
      {
        "name": "SouinResponseHandler",
        "path": "./middleware/souin-plugin.so"
      }
    ],
    "driver": "goplugin"
  },
  "config_data": {
    "httpcache": {
      "api": {
        "souin": {
          "enable": true
        }
      },
      "default_cache": {
        "ttl": "60s",
        "stale": "60m"
    },
      "log_level": "DEBUG"
    }
  },
  "active": true
}
```
if 'https://test.com' sends responses with header: 

```
"Cache-Control" : "max-age=120, stale-while-revalidate=36000"
```
First time misses the cache (expected)
Then for the next 60 secs the following requests are fetched from cache (also expected)
At this point after the cache ttl is reached I would expect the cache marked as stale for the next 60 mins, so that if I send another request immediately after with `stale-while-revalidate=36000` this would return stale content and revalidate the cache in background. 

However the following requests are simply a cache miss so that the response is refetched from upstream while the request is waiting. 

I also tried to add config:

```
"default_cache_control": "max-age=120, stale-while-revalidate=36000"
```
But still no success. 

Am I doing something wrong?

**Comment by darkweak** [comment]
Hello @acaporrini the Tyk plugin differs from the base middleware (because Tyk plugin doesn't as a basic middleware). I will have to update the plugin with the latest changes from the common middleware. I will have to write more Tyk e2e tests to ensure it has the same behaviour too.

Thank you for trying to use Souin inside Tyk and thank you for your feedback! 🙏

**Comment by acaporrini** [comment]
Hi @darkweak thank you a lot for quick reply and for looking into this. Do you maybe have an idea on when this will be implemented?

**Comment by darkweak** [comment]
Hello @acaporrini I apologize about my late answer. I don't find a way to handle that (because Tyk doesn't act as a classic middleware). The actual plugin behavior is like:
```
Tyk gateway request handled
        ↓
Load plugins
        ↓
SouinRequestHandler (it will keep in memory the stale response)
        ↓
Tries to connect to the upstream server
        ↓
SouinResponseHandler will write the stale response body, headers,...
        ↓
Writes the upstream response
```
Actually it writes the body twice (from the upstream and from the stale response)
I cannot short-circuit and I didn't find a way to prevent the body from being filled by the upstream server at the moment.
I don't know how to allow the gw to contact the upstream, serve the response from the cache but doesn't wait and doesn't write the upstream response.
Ping @buger @andyo-tyk @lonelycode @matiasinsaurralde if there is a way to do that.

**Comment by buger** [comment]
@darkweak wanna jump on quick debugging session? Ping me on leo@tyk.io, and we will figure out smth.

**Comment by darkweak** [comment]
@buger Did you received my email to plan a debugging session?

**Comment by buger** [comment]
Weird but no. I just sent you mail to darkweak@protonmail.com, to test if all works.

**Comment by darkweak** [comment]
Received, I just sent you another mail in response to your.

**Comment by darkweak** [comment]
Not possible with the actual middleware implementation in Tyk. Some possible ways we discussed with Leonid are not viable so this feature can not be supported while they're not allowing the asynchronous upstream request in a middleware and return a value before the response from the upstream.
