### ISSUE TITLE
Add image optimisation and asset compression

### ISSUE THREAD

**Issue by Allaux** [Darkweak/Souin#91]
Hello,
I think you can add an image optimiser to Souin with return jpeg/wepb depending on accept header provided by the client like this : https://github.com/agravelot/traefik-image-optimization

**Comment by Darkweak** [comment]
Hi @Allaux, I'll work on the Souin plugin integration in Træfik to be able to use it without the dev mode. I have to try this plugin to ensure it returns a vary header in the response. Otherwise I'll open a PR on the referred plugin because if it doesn't return a vary header Souin will serve the same content instead of the webp/jpg/any_other depending to the system.

**Comment by Darkweak** [comment]
@Allaux https://github.com/agravelot/traefik-image-optimization/issues/14#issuecomment-873474487
