### ISSUE TITLE
Tiered cache and suitability of Souin for processed asset requests caching

### ISSUE THREAD

**Issue by polarathene** [Darkweak/Souin#97]
Is tiered caching something that Souin might support? Where a fast memory cache is used, and a larger on disk cache?

One project I was looking into [imageproxy](https://github.com/willnorris/imageproxy) mentions a way of supporting this via the Go package [`twotier`](https://pkg.go.dev/github.com/die-net/lrucache/twotier).

A similar named project [`imgproxy`](https://github.com/imgproxy/imgproxy) is what I'd like to use, but they have no integrated support for a cache layer. I use Caddy as a reverse-proxy and saw you mention Souin on `cdp-cache` caddy plugin project.

Is Souin suitable for this type of processed image caching to avoid redundantly processing the same image requests too frequently? Or is squid/varnish/nuster more appropriate?

---

We have around 30GB of image data, but want to serve a variety of transforms (_size and image formats_), the website has image heavy pages (_most notably the main page which is updated frequently_), we exceed 10TB in monthly bandwidth traffic, thus I'm a little concerned about the resource trade-off of CPU+RAM for storage with no cache or memory cache being too small.

A disk cache will also survive service restarts without requiring resources to reprocess frequently accessed images, assuming that cache retention can be LRU or LFU based instead of evicted by an expiry time/age. Once transformed, these images can be assigned immutable and long-lived cache-control header for the client-side.

**Comment by Darkweak** [comment]
Hello @polarathene, thank for your interest about Souin.

I think, you could use Souin with the `EmbeddedOlric` or `Olric` provider. This way, it will store in memory and save on disk when it reaches the RAM limit. This way it will support the LRU based storage.

If you request your images using urls, Souin will be able to cache the image depending the query params.

It would be related to this issue I guess https://github.com/Darkweak/Souin/issues/62#issue-858535496 (cc @lucmichalski).

ATM it's not supported officially by Caddy as cache system, but in a near future it should be done.

**Comment by polarathene** [comment]
> It would be related to this issue I guess [#62 (comment)](https://github.com/Darkweak/Souin/issues/62#issue-858535496) (cc @lucmichalski).

Similar. My plan is to proxy existing asset URLs for some old software we run that we can use the URL to lookup the original image on disk and transform it via an image proxy service running on the server internally, that then provides the optimized image as a response back to Caddy, which then from what I understand goes through Souin to be cached for future requests to that URL.

If we had all transforms up front on disk for a static file server or CDN it would be between 100-500GiB, or alternatively with the image proxy, we process the image URL every request redundantly. Souin or similar seems an appropriate fit to cache the most actively requested image URLs, we're likely to still adopt an external CDN service as we only have a single server.

> ATM it's not supported officially by Caddy as cache system, but in a near future it should be done.

What is not supported by Caddy? My understanding is that Souin is usable as a Caddy plugin? I plan to try it in the next day or so.

> Souin will be able to cache the image depending the query params.

Is there more information about that constraint? I didn't see anything on the README regarding query params affecting caching. As long as the URL with params remains the same for a resource, it will not have any issues correct?

The cache layer is intended for the `imgproxy` processed results, a request to `imgproxy` service (internal, not publicly reachable) will be handled by Caddy, with no involvement from Souin. Requests from the website asset URLs would be picked up by Souin, providing query params to `imgproxy` to process if no cache hit.

**Comment by Darkweak** [comment]
> What is not supported by Caddy? My understanding is that Souin is usable as a Caddy plugin? I plan to try it in the next day or so. 
I said it's not officially supported by Caddy because that's not in the official documentation. But be sure everything is working like a charm.

The part about the query params would say:
You send a request on your `imgproxy` service with a `height` and a `width` parameters to resize `my_first_image` (GET https://imgproxy.com/my_first_image?height=400&width=200) then Souin will store the resized image and serve from cache `my_first_image` resized.
If a user send a GET request on `https://imgproxy.com/my_first_image?height=800&width=400` for example, then Souin will send the request to the service to build the resized image.

It should be transparent for you, you won't have to do anything I guess.

Wait tomorrow to try Souin, I'm currently working on the refactoring about the request coalescing implementation. I should finish this tonight.

**Comment by Darkweak** [comment]
Update: The new management system for the request coalescing is available on master @polarathene

**Comment by Darkweak** [comment]
@polarathene if you can wait for another KV (instead of `Olric`) storage with a file cache in case you're over the declared memory limit, I'll implement the fact you can fully configure `Badger` in few days.
ATM I'm on another issue/feature but it shouldn't take more than a day so after that I should be able to dev this part.
